/**
 * GENERATED FILE — do not edit.
 * Run `npm run gen:hooks` after changing anything under scripts/*.sh.
 * Source of truth: scripts/co-stop-hook.sh, scripts/co-notification-hook.sh.
 */

export const HOOK_SCRIPT_SOURCES: Readonly<Record<string, string>> = {
	"co-stop-hook.sh": "#!/usr/bin/env bash\n# Claude Code Stop hook — writes a signal file for Orchestrator plugin.\n# Receives JSON on stdin with session_id, transcript_path, cwd, etc.\n# Detects the current tmux session name and writes a signal to /tmp/co-stop/.\n# Reads transcript JSONL to classify stop as \"done\" or \"asking\".\n\nset -euo pipefail\n\n# Overridable so tests can drive the hook without writing into the\n# live signal directory a running plugin is consuming.\nSIGNAL_DIR=\"${CO_SIGNAL_DIR:-/tmp/co-stop}\"\nmkdir -p \"$SIGNAL_DIR\"\n\nINPUT=$(cat)\n\nTMUX_SESSION=$(tmux display-message -p '#S' 2>/dev/null || echo \"unknown\")\n# Vault tag set by the plugin at session create/attach — lets each vault's\n# watcher consume only its own signals in the shared signal dir.\nCO_VAULT=$(tmux display-message -p '#{@co_vault}' 2>/dev/null || echo \"\")\nTIMESTAMP=$(date +%s)\n\nSIGNAL=$(printf '%s' \"$INPUT\" | /usr/bin/python3 -c \"\nimport sys, json, re, os\n\ndata = json.load(sys.stdin)\ndata['tmux_session'] = '$TMUX_SESSION'\ndata['timestamp'] = $TIMESTAMP\ndata['vault'] = '$CO_VAULT'\n\nstop_reason = 'done'\ntp = data.get('transcript_path', '')\nif tp and os.path.isfile(tp):\n    try:\n        with open(tp, 'r') as f:\n            lines = f.readlines()\n        for line in reversed(lines):\n            try:\n                entry = json.loads(line)\n            except Exception:\n                continue\n            if entry.get('type') != 'assistant':\n                continue\n            content = entry.get('message', {}).get('content', [])\n            text = '\\n'.join(\n                c.get('text', '') for c in content\n                if isinstance(c, dict) and c.get('type') == 'text'\n            )\n            if not text:\n                break\n            tail = text[-500:]\n            if re.search(r'[Yy]/[Nn]', tail):\n                stop_reason = 'asking'\n            elif re.search(r'\\?\\s*$', tail, re.MULTILINE):\n                stop_reason = 'asking'\n            break\n    except Exception:\n        pass\n\ndata['stop_reason'] = stop_reason\njson.dump(data, sys.stdout)\n\")\n\n# Atomic write: stage to .tmp then mv. Otherwise the watcher can read the\n# zero-byte file mid-write and silently drop the signal.\nSIGNAL_FILE=\"$SIGNAL_DIR/${TIMESTAMP}-${TMUX_SESSION}.json\"\necho \"$SIGNAL\" > \"$SIGNAL_FILE.tmp\"\nmv \"$SIGNAL_FILE.tmp\" \"$SIGNAL_FILE\"\n",
	"co-notification-hook.sh": "#!/usr/bin/env bash\n# Claude Code Notification hook — writes an \"asking\" signal for the\n# Orchestrator plugin when Claude requests permission.\n#\n# Only permission-style notifications are forwarded: the generic\n# \"waiting for your input\" idle notification fires 60s after any stop\n# and would mislabel a normally idle session as waiting_for_user.\n\nset -euo pipefail\n\n# Overridable so tests can drive the hook without writing into the\n# live signal directory a running plugin is consuming.\nSIGNAL_DIR=\"${CO_SIGNAL_DIR:-/tmp/co-stop}\"\nmkdir -p \"$SIGNAL_DIR\"\n\nINPUT=$(cat)\n\nTMUX_SESSION=$(tmux display-message -p '#S' 2>/dev/null || echo \"unknown\")\nCO_VAULT=$(tmux display-message -p '#{@co_vault}' 2>/dev/null || echo \"\")\nTIMESTAMP=$(date +%s)\n\nSIGNAL=$(printf '%s' \"$INPUT\" | /usr/bin/python3 -c \"\nimport sys, json\n\ndata = json.load(sys.stdin)\nmessage = str(data.get('message', ''))\nif 'permission' not in message.lower():\n    sys.exit(0)\n\ndata['tmux_session'] = '$TMUX_SESSION'\ndata['timestamp'] = $TIMESTAMP\ndata['vault'] = '$CO_VAULT'\ndata['stop_reason'] = 'asking'\njson.dump(data, sys.stdout)\n\")\n\nif [ -z \"$SIGNAL\" ]; then\n    exit 0\nfi\n\n# Atomic write (see co-stop-hook.sh). The -notify suffix keeps a Stop\n# signal in the same second from being overwritten.\nSIGNAL_FILE=\"$SIGNAL_DIR/${TIMESTAMP}-${TMUX_SESSION}-notify.json\"\necho \"$SIGNAL\" > \"$SIGNAL_FILE.tmp\"\nmv \"$SIGNAL_FILE.tmp\" \"$SIGNAL_FILE\"\n",
};
